name: Validate CloudFormation Templates
on:
  pull_request:
    branches:
      - main
  push:
    branches-ignore:
      - 'main'
  workflow_dispatch:
  
jobs:
  validate-cfn-templates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install cfn-lint
        run: |
          pip install cfn-lint
      
      - name: Lint CloudFormation templates
        run: |
          cfn-lint infra/domain.yml