name: test assume role
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  create-and-review-changeset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: us-east-1

      - name: Describe Changeset
        uses: Blue-Pix/describe-cfn-change-set@v2.1
        with:
          stack_name: DCO-Network
          template_body: /infra/domain.yml

  Execute-changeset:
    runs-on: ubuntu-latest	
    needs: create-and-review-changeset
    if: success()
    steps:
      - name: Configure AWS credentials using OIDC    
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: us-east-1

      - name: Execute CloudFormation Change Set
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: DCO-Network
          template: ./infra/domain.yml
          no-fail-on-empty-changeset: "1"
